# Generated by Django 3.1.6 on 2021-02-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210203_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Cake', 'Cake'), ('Bread', 'Bread'), ('Bread', 'Bread')], max_length=200, null=True),
        ),
    ]
