# Generated by Django 3.1.6 on 2021-02-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210204_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='jpeg', upload_to='images/'),
        ),
    ]
